name: 'Install GCC'
inputs:
  version:
    description: 'Version to install'
    required: false
    default: 13
runs:
  using: 'composite'
  steps:
    - name: Install
      shell: bash
      run: |
        sudo apt-get install -y gcc-${{ inputs.version }} g++-${{ inputs.version }}

