name: Static Analysis

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  clang-tidy:
    runs-on: ubuntu-22.04
    
    env:
      GCC_VER: 13
      CLANG_VER: 18
      
    strategy:
      fail-fast: false
        
    steps:
      - name: Checkout repository from github
        uses: actions/checkout@v4

      - name: Install gcc-${{ env.GCC_VER }}
        uses: ./.github/actions/install-gcc

      - name: Install clang-${{ env.CLANG_VER }}
        uses: ./.github/actions/install-clang 
        with:
          version: ${{ env.CLANG_VER }}
          clang-tidy: true

      - name: Install APT packages
        uses: ./.github/actions/install-apt-packages

      - name: Setup Conan
        id: setup-conan
        uses: ./.github/actions/setup-conan
        with:
          compiler: clang
          compiler-version: ${{ env.CLANG_VER }}
          build-type: Debug

      - name: Fetch dependencies
        run: |
          COMPILER_NAME=clang COMPILER_VER=${{ env.CLANG_VER }} conan install . --build=missing --profile=ci/conan/static-analysis

      - name: Configure CMake
        run: |
          cmake -DPAWN_ENABLE_CLANG_TIDY=ON --preset debug

      - name: Build
        run: |
          cmake --build --preset=debug

  iwyu:
    runs-on: ubuntu-22.04
    
    env:
      GCC_VER: 13
      CLANG_VER: 18
      
    strategy:
      fail-fast: false
        
    steps:
      - name: Checkout repository from github
        uses: actions/checkout@v4

      - name: Install gcc-${{ env.GCC_VER }}
        uses: ./.github/actions/install-gcc

      - name: Install clang-${{ env.CLANG_VER }}
        uses: ./.github/actions/install-clang 
        with:
          dev: true

      - name: Install APT packages
        uses: ./.github/actions/install-apt-packages

      - name: Install IWYU
        uses: ./.github/actions/install-iwyu

      - name: Setup Conan
        id: setup-conan
        uses: ./.github/actions/setup-conan
        with:
          compiler: clang
          compiler-version: ${{ env.CLANG_VER }}
          build-type: Debug

      - name: Fetch dependencies
        run: |
          COMPILER_NAME=clang COMPILER_VER=${{ env.CLANG_VER }} conan install . --build=missing --profile=ci/conan/static-analysis

      - name: Configure CMake
        run: |
          cmake -DPAWN_ENABLE_IWYU=ON --preset debug

      - name: Build
        run: |
          cmake --build --preset=debug

  gcc-analyzer:
    runs-on: ubuntu-22.04
    
    env:
      GCC_VER: 13
      
    strategy:
      fail-fast: false
        
    steps:
      - name: Checkout repository from github
        uses: actions/checkout@v4

      - name: Install gcc-${{ env.GCC_VER }}
        uses: ./.github/actions/install-gcc

      - name: Install APT packages
        uses: ./.github/actions/install-apt-packages

      - name: Setup Conan
        id: setup-conan
        uses: ./.github/actions/setup-conan
        with:
          compiler: gcc
          compiler-version: ${{ env.GCC_VER }}
          build-type: Debug             

      - name: Fetch dependencies
        run: |
          COMPILER_NAME=gcc COMPILER_VER=${{ env.GCC_VER }} conan install . --build=missing --profile=ci/conan/static-analysis

      - name: Configure CMake
        run: |
          cmake -DPAWN_ENABLE_COMPILER_STATIC_ANALYSIS=ON --preset debug

      - name: Build
        run: |
          cmake --build --preset=debug

  cppcheck:
    runs-on: ubuntu-22.04
    
    env:
      GCC_VER: 13
      
    strategy:
      fail-fast: false
        
    steps:
      - name: Checkout repository from github
        uses: actions/checkout@v4

      - name: Install gcc-${{ env.GCC_VER }}
        uses: ./.github/actions/install-gcc

      - name: Install APT packages
        uses: ./.github/actions/install-apt-packages

      - name: Install Cppcheck
        uses: ./.github/actions/install-cppcheck

      - name: Setup Conan
        id: setup-conan
        uses: ./.github/actions/setup-conan
        with:
          compiler: gcc
          compiler-version: ${{ env.GCC_VER }}
          build-type: Debug             

      - name: Fetch dependencies
        run: |
          COMPILER_NAME=gcc COMPILER_VER=${{ env.GCC_VER }} conan install . --build=missing --profile=ci/conan/static-analysis

      - name: Configure CMake
        run: |
          cmake -DPAWN_ENABLE_CPPCHECK=ON --preset debug

      - name: Build
        run: |
          cmake --build --preset=debug

  msvc-analyze:
    runs-on: windows-2022

    env:
      CONAN_PROFILE: msvc-2022

    strategy:
      fail-fast: false

    steps:
      - name: Initialize
        run: |
          git config --global core.autocrlf input
          
      - name: Checkout repository from github
        uses: actions/checkout@v4

      - name: Install Vulkan SDK
        uses: ./.github/actions/install-vulkan-sdk

      - name: Setup Conan
        id: setup-conan
        uses: ./.github/actions/setup-conan
        with:
          compiler: msvc
          compiler-version: 2022
          build-type: Debug

      - name: Fetch dependencies
        run: |
          conan install . --build=missing --profile=ci/conan/msvc-analyze

      - name: Configure CMake
        run: |
          cmake -DPAWN_ENABLE_COMPILER_STATIC_ANALYSIS=ON --preset default
          
      - name: Build
        run: |
          cmake --build --preset=multi-debug

